name = "kp-chatbot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://www.kp-glass.ca,https://kp-glass.ca,https://jordan904.github.io,http://localhost:3000,http://localhost:3002"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CHAT_LOGS"
id = "d7984fba4a524f7497f7b1028dd2c472"
